// Code generated by 'ccgo sys/vfs/gen.c -crt-import-path  -export-defines  -export-enums  -export-externs X -export-fields F -export-structs  -export-typedefs  -header -hide _OSSwapInt16,_OSSwapInt32,_OSSwapInt64 -ignore-unsupported-alignment -o sys/vfs/vfs_linux_amd64.go -pkgname vfs', DO NOT EDIT.

package vfs

var CAPI = map[string]struct{}{}
