// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAlarmConfig = "alarm_config"

// AlarmConfig mapped from table <alarm_config>
type AlarmConfig struct {
	ID                  string    `gorm:"column:id;primaryKey" json:"id"`
	Name                string    `gorm:"column:name;not null;comment:告警名称" json:"name"`                                    // 告警名称
	Description         *string   `gorm:"column:description;comment:告警描述" json:"description"`                               // 告警描述
	AlarmLevel          string    `gorm:"column:alarm_level;not null;comment:告警级别H: 高M: 中L: 低" json:"alarm_level"`          // 告警级别H: 高M: 中L: 低
	NotificationGroupID string    `gorm:"column:notification_group_id;not null;comment:通知组id" json:"notification_group_id"` // 通知组id
	CreatedAt           time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt           time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	TenantID            string    `gorm:"column:tenant_id;not null" json:"tenant_id"`
	Remark              *string   `gorm:"column:remark" json:"remark"`
	Enabled             string    `gorm:"column:enabled;not null;comment:是否启用Y-启用N-停止" json:"enabled"` // 是否启用Y-启用N-停止
}

// TableName AlarmConfig's table name
func (*AlarmConfig) TableName() string {
	return TableNameAlarmConfig
}
