// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysDict = "sys_dict"

// SysDict mapped from table <sys_dict>
type SysDict struct {
	ID        string    `gorm:"column:id;primaryKey;comment:主键ID" json:"id"`               // 主键ID
	DictCode  string    `gorm:"column:dict_code;not null;comment:字典标识符" json:"dict_code"`  // 字典标识符
	DictValue string    `gorm:"column:dict_value;not null;comment:字典值" json:"dict_value"`  // 字典值
	CreatedAt time.Time `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"` // 创建时间
	Remark    *string   `gorm:"column:remark;comment:备注" json:"remark"`                    // 备注
}

// TableName SysDict's table name
func (*SysDict) TableName() string {
	return TableNameSysDict
}
