// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVisPlugin = "vis_plugin"

// VisPlugin mapped from table <vis_plugin>
type VisPlugin struct {
	ID                string  `gorm:"column:id;primaryKey" json:"id"`
	TenantID          string  `gorm:"column:tenant_id;not null;comment:租户id" json:"tenant_id"`          // 租户id
	PluginName        string  `gorm:"column:plugin_name;not null;comment:可视化插件名称" json:"plugin_name"`   // 可视化插件名称
	PluginDescription *string `gorm:"column:plugin_description;comment:插件描述" json:"plugin_description"` // 插件描述
	CreateAt          *int64  `gorm:"column:create_at" json:"create_at"`
	Remark            *string `gorm:"column:remark" json:"remark"`
}

// TableName VisPlugin's table name
func (*VisPlugin) TableName() string {
	return TableNameVisPlugin
}
