// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAlarmInfo = "alarm_info"

// AlarmInfo mapped from table <alarm_info>
type AlarmInfo struct {
	ID               string    `gorm:"column:id;primaryKey" json:"id"`
	AlarmConfigID    string    `gorm:"column:alarm_config_id;not null;comment:告警配置id" json:"alarm_config_id"`                        // 告警配置id
	Name             string    `gorm:"column:name;not null;comment:告警名称" json:"name"`                                                // 告警名称
	AlarmTime        time.Time `gorm:"column:alarm_time;not null;comment:告警时间" json:"alarm_time"`                                    // 告警时间
	Description      *string   `gorm:"column:description;comment:告警描述" json:"description"`                                           // 告警描述
	Content          *string   `gorm:"column:content;comment:内容" json:"content"`                                                     // 内容
	Processor        *string   `gorm:"column:processor;comment:处理人id" json:"processor"`                                              // 处理人id
	ProcessingResult string    `gorm:"column:processing_result;not null;comment:处理结果DOP-已处理UND-未处理IGN-已忽略" json:"processing_result"` // 处理结果DOP-已处理UND-未处理IGN-已忽略
	TenantID         string    `gorm:"column:tenant_id;not null;comment:租户id" json:"tenant_id"`                                      // 租户id
	Remark           *string   `gorm:"column:remark" json:"remark"`
	AlarmLevel       *string   `gorm:"column:alarm_level;comment:告警级别L M H" json:"alarm_level"` // 告警级别L M H
}

// TableName AlarmInfo's table name
func (*AlarmInfo) TableName() string {
	return TableNameAlarmInfo
}
