// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBoard = "boards"

// Board mapped from table <boards>
type Board struct {
	ID          string    `gorm:"column:id;primaryKey;comment:Id" json:"id"`                   // Id
	Name        string    `gorm:"column:name;not null;comment:看板名称" json:"name"`               // 看板名称
	Config      *string   `gorm:"column:config;default:{};comment:看板配置" json:"config"`         // 看板配置
	TenantID    string    `gorm:"column:tenant_id;not null;comment:租户id（唯一）" json:"tenant_id"` // 租户id（唯一）
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	HomeFlag    string    `gorm:"column:home_flag;not null;comment:首页标志默认N，Y" json:"home_flag"` // 首页标志默认N，Y
	Description *string   `gorm:"column:description;comment:描述" json:"description"`             // 描述
	Remark      *string   `gorm:"column:remark;comment:备注" json:"remark"`                       // 备注
	MenuFlag    *string   `gorm:"column:menu_flag;comment:菜单标志默认N，Y" json:"menu_flag"`          // 菜单标志默认N，Y
	VisType     *string   `gorm:"column:vis_type;comment:可视化类型" json:"vis_type"`                // 可视化类型
}

// TableName Board's table name
func (*Board) TableName() string {
	return TableNameBoard
}
