// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDeviceStatusHistory = "device_status_history"

// DeviceStatusHistory mapped from table <device_status_history>
type DeviceStatusHistory struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TenantID   string    `gorm:"column:tenant_id;not null;comment:租户ID" json:"tenant_id"`       // 租户ID
	DeviceID   string    `gorm:"column:device_id;not null;comment:设备ID" json:"device_id"`       // 设备ID
	Status     int16     `gorm:"column:status;not null;comment:状态: 0-离线 1-在线" json:"status"`    // 状态: 0-离线 1-在线
	ChangeTime time.Time `gorm:"column:change_time;not null;comment:状态变更时间" json:"change_time"` // 状态变更时间
}

// TableName DeviceStatusHistory's table name
func (*DeviceStatusHistory) TableName() string {
	return TableNameDeviceStatusHistory
}
