package model

const (
	DEVICE_TRIGGER_CONDITION_TYPE_ONE      = "10" //单个设备
	DEVICE_TRIGGER_CONDITION_TYPE_MULTIPLE = "11" //单类设备
	DEVICE_TRIGGER_CONDITION_TYPE_TIME     = "22" //时间范围
	//条件类型
	TRIGGER_PARAM_TYPE_TEL       = "TEL"       //遥测TEL
	TRIGGER_PARAM_TYPE_TELEMETRY = "TELEMETRY" //遥测TEL
	TRIGGER_PARAM_TYPE_ATTR      = "ATTR"      //属性ATTR
	TRIGGER_PARAM_TYPE_EVT       = "EVT"       //事件EVT
	TRIGGER_PARAM_TYPE_STATUS    = "STATUS"    //状态STATUS

	//运算符
	CONDITION_TRIGGER_OPERATOR_EQ      = "="       //等于
	CONDITION_TRIGGER_OPERATOR_NEQ     = "!="      //不等于
	CONDITION_TRIGGER_OPERATOR_GT      = ">"       //大于
	CONDITION_TRIGGER_OPERATOR_LT      = "<"       //大于
	CONDITION_TRIGGER_OPERATOR_GTE     = ">="      //大于
	CONDITION_TRIGGER_OPERATOR_LTE     = "<="      //大于
	CONDITION_TRIGGER_OPERATOR_BETWEEN = "between" //大于
	CONDITION_TRIGGER_OPERATOR_IN      = "in"      //大于

	//动作类型
	AUTOMATE_ACTION_TYPE_ONE      = "10" //单个设备
	AUTOMATE_ACTION_TYPE_MULTIPLE = "11" //单类设备
	AUTOMATE_ACTION_TYPE_SCENE    = "20" //激活场景
	AUTOMATE_ACTION_TYPE_ALARM    = "30" //告警
	AUTOMATE_ACTION_TYPE_SERVICE  = "40" //服务

)
