// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDevice = "devices"

// Device mapped from table <devices>
type Device struct {
	ID             string     `gorm:"column:id;primaryKey;comment:Id" json:"id"`                                                      // Id
	Name           *string    `gorm:"column:name;comment:设备名称" json:"name"`                                                           // 设备名称
	Voucher        string     `gorm:"column:voucher;not null;comment:凭证" json:"voucher"`                                              // 凭证
	TenantID       string     `gorm:"column:tenant_id;not null;comment:租户id，外键，删除时阻止" json:"tenant_id"`                               // 租户id，外键，删除时阻止
	IsEnabled      string     `gorm:"column:is_enabled;not null;comment:启用/禁用 enabled-启用 disabled-禁用 默认禁用，激活后默认启用" json:"is_enabled"` // 启用/禁用 enabled-启用 disabled-禁用 默认禁用，激活后默认启用
	ActivateFlag   string     `gorm:"column:activate_flag;not null;comment:激活标志inactive-未激活 active-已激活" json:"activate_flag"`         // 激活标志inactive-未激活 active-已激活
	CreatedAt      *time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                               // 创建时间
	UpdateAt       *time.Time `gorm:"column:update_at;comment:更新时间" json:"update_at"`                                                 // 更新时间
	DeviceNumber   string     `gorm:"column:device_number;not null;comment:设备编号 没送默认和token一样" json:"device_number"`                   // 设备编号 没送默认和token一样
	ProductID      *string    `gorm:"column:product_id;comment:产品id 外键，删除时阻止" json:"product_id"`                                      // 产品id 外键，删除时阻止
	ParentID       *string    `gorm:"column:parent_id;comment:子设备的网关id" json:"parent_id"`                                             // 子设备的网关id
	Protocol       *string    `gorm:"column:protocol;comment:通讯协议" json:"protocol"`                                                   // 通讯协议
	Label          *string    `gorm:"column:label;comment:标签 单标签，英文逗号隔开" json:"label"`                                                // 标签 单标签，英文逗号隔开
	Location       *string    `gorm:"column:location;comment:地理位置" json:"location"`                                                   // 地理位置
	SubDeviceAddr  *string    `gorm:"column:sub_device_addr;comment:子设备地址" json:"sub_device_addr"`                                    // 子设备地址
	CurrentVersion *string    `gorm:"column:current_version;comment:当前固件版本" json:"current_version"`                                   // 当前固件版本
	AdditionalInfo *string    `gorm:"column:additional_info;default:{};comment:其他信息 阈值、图片等" json:"additional_info"`                   // 其他信息 阈值、图片等
	ProtocolConfig *string    `gorm:"column:protocol_config;default:{};comment:协议表单配置" json:"protocol_config"`                        // 协议表单配置
	Remark1        *string    `gorm:"column:remark1" json:"remark1"`
	Remark2        *string    `gorm:"column:remark2" json:"remark2"`
	Remark3        *string    `gorm:"column:remark3" json:"remark3"`
	/*
		设备配置id（外键）


	*/
	DeviceConfigID *string `gorm:"column:device_config_id;comment:设备配置id（外键）\n\n" json:"device_config_id"`
	/*
		批次编号

	*/
	BatchNumber     *string    `gorm:"column:batch_number;comment:批次编号\n" json:"batch_number"`
	ActivateAt      *time.Time `gorm:"column:activate_at;comment:激活日期" json:"activate_at"`                // 激活日期
	IsOnline        int16      `gorm:"column:is_online;not null;comment:是否在线 1-在线 0-离线" json:"is_online"` // 是否在线 1-在线 0-离线
	AccessWay       *string    `gorm:"column:access_way;comment:接入方式A-通过协议 B通过服务" json:"access_way"`      // 接入方式A-通过协议 B通过服务
	Description     *string    `gorm:"column:description;comment:描述" json:"description"`                  // 描述
	ServiceAccessID *string    `gorm:"column:service_access_id" json:"service_access_id"`
	LastOfflineTime *time.Time `gorm:"column:last_offline_time;comment:上次离线时间" json:"last_offline_time"` // 上次离线时间
}

// TableName Device's table name
func (*Device) TableName() string {
	return TableNameDevice
}
