// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameExpectedData = "expected_datas"

// ExpectedData mapped from table <expected_datas>
type ExpectedData struct {
	ID         string     `gorm:"column:id;primaryKey;comment:指令唯一标识符(UUID)" json:"id"`                                            // 指令唯一标识符(UUID)
	DeviceID   string     `gorm:"column:device_id;not null;comment:目标设备ID" json:"device_id"`                                       // 目标设备ID
	SendType   string     `gorm:"column:send_type;not null;comment:指令类型(e.g., telemetry, attribute, command)" json:"send_type"`    // 指令类型(e.g., telemetry, attribute, command)
	Payload    string     `gorm:"column:payload;not null;comment:指令内容(具体指令参数)" json:"payload"`                                     // 指令内容(具体指令参数)
	CreatedAt  time.Time  `gorm:"column:created_at;not null;comment:指令生成时间" json:"created_at"`                                     // 指令生成时间
	SendTime   *time.Time `gorm:"column:send_time;comment:指令实际发送时间(如果已发送)" json:"send_time"`                                       // 指令实际发送时间(如果已发送)
	Status     string     `gorm:"column:status;not null;default:pending;comment:指令状态(pending, sent, expired)，默认待发送" json:"status"` // 指令状态(pending, sent, expired)，默认待发送
	Message    *string    `gorm:"column:message;comment:状态附加信息(如发送失败的原因)" json:"message"`                                          // 状态附加信息(如发送失败的原因)
	ExpiryTime *time.Time `gorm:"column:expiry_time;comment:指令过期时间(可选)" json:"expiry_time"`                                        // 指令过期时间(可选)
	Label      *string    `gorm:"column:label;comment:指令标签(可选)" json:"label"`                                                      // 指令标签(可选)
	TenantID   string     `gorm:"column:tenant_id;not null;comment:租户ID（用于多租户系统）" json:"tenant_id"`                                // 租户ID（用于多租户系统）
}

// TableName ExpectedData's table name
func (*ExpectedData) TableName() string {
	return TableNameExpectedData
}
