// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTelemetrySetLog = "telemetry_set_logs"

// TelemetrySetLog mapped from table <telemetry_set_logs>
type TelemetrySetLog struct {
	ID            string    `gorm:"column:id;primaryKey" json:"id"`
	DeviceID      string    `gorm:"column:device_id;not null;comment:设备id（外键-关联删除）" json:"device_id"`      // 设备id（外键-关联删除）
	OperationType *string   `gorm:"column:operation_type;comment:操作类型1-手动操作 2-自动触发" json:"operation_type"` // 操作类型1-手动操作 2-自动触发
	Datum         *string   `gorm:"column:data;comment:发送内容" json:"data"`                                  // 发送内容
	Status        *string   `gorm:"column:status;comment:1-发送成功 2-失败" json:"status"`                       // 1-发送成功 2-失败
	ErrorMessage  *string   `gorm:"column:error_message;comment:错误信息" json:"error_message"`                // 错误信息
	CreatedAt     time.Time `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`             // 创建时间
	UserID        *string   `gorm:"column:user_id;comment:操作用户" json:"user_id"`                            // 操作用户
	Description   *string   `gorm:"column:description;comment:描述" json:"description"`                      // 描述
}

// TableName TelemetrySetLog's table name
func (*TelemetrySetLog) TableName() string {
	return TableNameTelemetrySetLog
}
