// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"project/internal/model"
)

func newDeviceTopicMapping(db *gorm.DB, opts ...gen.DOOption) deviceTopicMapping {
	_deviceTopicMapping := deviceTopicMapping{}

	_deviceTopicMapping.deviceTopicMappingDo.UseDB(db, opts...)
	_deviceTopicMapping.deviceTopicMappingDo.UseModel(&model.DeviceTopicMapping{})

	tableName := _deviceTopicMapping.deviceTopicMappingDo.TableName()
	_deviceTopicMapping.ALL = field.NewAsterisk(tableName)
	_deviceTopicMapping.ID = field.NewInt64(tableName, "id")
	_deviceTopicMapping.DeviceConfigID = field.NewString(tableName, "device_config_id")
	_deviceTopicMapping.Name = field.NewString(tableName, "name")
	_deviceTopicMapping.Direction = field.NewString(tableName, "direction")
	_deviceTopicMapping.SourceTopic = field.NewString(tableName, "source_topic")
	_deviceTopicMapping.TargetTopic = field.NewString(tableName, "target_topic")
	_deviceTopicMapping.Priority = field.NewInt32(tableName, "priority")
	_deviceTopicMapping.Enabled = field.NewBool(tableName, "enabled")
	_deviceTopicMapping.Description = field.NewString(tableName, "description")
	_deviceTopicMapping.CreatedAt = field.NewTime(tableName, "created_at")
	_deviceTopicMapping.UpdatedAt = field.NewTime(tableName, "updated_at")
	_deviceTopicMapping.DataIdentifier = field.NewString(tableName, "data_identifier")

	_deviceTopicMapping.fillFieldMap()

	return _deviceTopicMapping
}

type deviceTopicMapping struct {
	deviceTopicMappingDo

	ALL            field.Asterisk
	ID             field.Int64
	DeviceConfigID field.String
	Name           field.String
	Direction      field.String
	SourceTopic    field.String
	TargetTopic    field.String
	Priority       field.Int32
	Enabled        field.Bool
	Description    field.String
	CreatedAt      field.Time
	UpdatedAt      field.Time
	DataIdentifier field.String

	fieldMap map[string]field.Expr
}

func (d deviceTopicMapping) Table(newTableName string) *deviceTopicMapping {
	d.deviceTopicMappingDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deviceTopicMapping) As(alias string) *deviceTopicMapping {
	d.deviceTopicMappingDo.DO = *(d.deviceTopicMappingDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deviceTopicMapping) updateTableName(table string) *deviceTopicMapping {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.DeviceConfigID = field.NewString(table, "device_config_id")
	d.Name = field.NewString(table, "name")
	d.Direction = field.NewString(table, "direction")
	d.SourceTopic = field.NewString(table, "source_topic")
	d.TargetTopic = field.NewString(table, "target_topic")
	d.Priority = field.NewInt32(table, "priority")
	d.Enabled = field.NewBool(table, "enabled")
	d.Description = field.NewString(table, "description")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")
	d.DataIdentifier = field.NewString(table, "data_identifier")

	d.fillFieldMap()

	return d
}

func (d *deviceTopicMapping) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deviceTopicMapping) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 12)
	d.fieldMap["id"] = d.ID
	d.fieldMap["device_config_id"] = d.DeviceConfigID
	d.fieldMap["name"] = d.Name
	d.fieldMap["direction"] = d.Direction
	d.fieldMap["source_topic"] = d.SourceTopic
	d.fieldMap["target_topic"] = d.TargetTopic
	d.fieldMap["priority"] = d.Priority
	d.fieldMap["enabled"] = d.Enabled
	d.fieldMap["description"] = d.Description
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
	d.fieldMap["data_identifier"] = d.DataIdentifier
}

func (d deviceTopicMapping) clone(db *gorm.DB) deviceTopicMapping {
	d.deviceTopicMappingDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deviceTopicMapping) replaceDB(db *gorm.DB) deviceTopicMapping {
	d.deviceTopicMappingDo.ReplaceDB(db)
	return d
}

type deviceTopicMappingDo struct{ gen.DO }

type IDeviceTopicMappingDo interface {
	gen.SubQuery
	Debug() IDeviceTopicMappingDo
	WithContext(ctx context.Context) IDeviceTopicMappingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeviceTopicMappingDo
	WriteDB() IDeviceTopicMappingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeviceTopicMappingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeviceTopicMappingDo
	Not(conds ...gen.Condition) IDeviceTopicMappingDo
	Or(conds ...gen.Condition) IDeviceTopicMappingDo
	Select(conds ...field.Expr) IDeviceTopicMappingDo
	Where(conds ...gen.Condition) IDeviceTopicMappingDo
	Order(conds ...field.Expr) IDeviceTopicMappingDo
	Distinct(cols ...field.Expr) IDeviceTopicMappingDo
	Omit(cols ...field.Expr) IDeviceTopicMappingDo
	Join(table schema.Tabler, on ...field.Expr) IDeviceTopicMappingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceTopicMappingDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeviceTopicMappingDo
	Group(cols ...field.Expr) IDeviceTopicMappingDo
	Having(conds ...gen.Condition) IDeviceTopicMappingDo
	Limit(limit int) IDeviceTopicMappingDo
	Offset(offset int) IDeviceTopicMappingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceTopicMappingDo
	Unscoped() IDeviceTopicMappingDo
	Create(values ...*model.DeviceTopicMapping) error
	CreateInBatches(values []*model.DeviceTopicMapping, batchSize int) error
	Save(values ...*model.DeviceTopicMapping) error
	First() (*model.DeviceTopicMapping, error)
	Take() (*model.DeviceTopicMapping, error)
	Last() (*model.DeviceTopicMapping, error)
	Find() ([]*model.DeviceTopicMapping, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceTopicMapping, err error)
	FindInBatches(result *[]*model.DeviceTopicMapping, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DeviceTopicMapping) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeviceTopicMappingDo
	Assign(attrs ...field.AssignExpr) IDeviceTopicMappingDo
	Joins(fields ...field.RelationField) IDeviceTopicMappingDo
	Preload(fields ...field.RelationField) IDeviceTopicMappingDo
	FirstOrInit() (*model.DeviceTopicMapping, error)
	FirstOrCreate() (*model.DeviceTopicMapping, error)
	FindByPage(offset int, limit int) (result []*model.DeviceTopicMapping, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeviceTopicMappingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deviceTopicMappingDo) Debug() IDeviceTopicMappingDo {
	return d.withDO(d.DO.Debug())
}

func (d deviceTopicMappingDo) WithContext(ctx context.Context) IDeviceTopicMappingDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deviceTopicMappingDo) ReadDB() IDeviceTopicMappingDo {
	return d.Clauses(dbresolver.Read)
}

func (d deviceTopicMappingDo) WriteDB() IDeviceTopicMappingDo {
	return d.Clauses(dbresolver.Write)
}

func (d deviceTopicMappingDo) Session(config *gorm.Session) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Session(config))
}

func (d deviceTopicMappingDo) Clauses(conds ...clause.Expression) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deviceTopicMappingDo) Returning(value interface{}, columns ...string) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deviceTopicMappingDo) Not(conds ...gen.Condition) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deviceTopicMappingDo) Or(conds ...gen.Condition) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deviceTopicMappingDo) Select(conds ...field.Expr) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deviceTopicMappingDo) Where(conds ...gen.Condition) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deviceTopicMappingDo) Order(conds ...field.Expr) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deviceTopicMappingDo) Distinct(cols ...field.Expr) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deviceTopicMappingDo) Omit(cols ...field.Expr) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deviceTopicMappingDo) Join(table schema.Tabler, on ...field.Expr) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deviceTopicMappingDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceTopicMappingDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deviceTopicMappingDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeviceTopicMappingDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deviceTopicMappingDo) Group(cols ...field.Expr) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deviceTopicMappingDo) Having(conds ...gen.Condition) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deviceTopicMappingDo) Limit(limit int) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deviceTopicMappingDo) Offset(offset int) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deviceTopicMappingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deviceTopicMappingDo) Unscoped() IDeviceTopicMappingDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deviceTopicMappingDo) Create(values ...*model.DeviceTopicMapping) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deviceTopicMappingDo) CreateInBatches(values []*model.DeviceTopicMapping, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deviceTopicMappingDo) Save(values ...*model.DeviceTopicMapping) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deviceTopicMappingDo) First() (*model.DeviceTopicMapping, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceTopicMapping), nil
	}
}

func (d deviceTopicMappingDo) Take() (*model.DeviceTopicMapping, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceTopicMapping), nil
	}
}

func (d deviceTopicMappingDo) Last() (*model.DeviceTopicMapping, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceTopicMapping), nil
	}
}

func (d deviceTopicMappingDo) Find() ([]*model.DeviceTopicMapping, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeviceTopicMapping), err
}

func (d deviceTopicMappingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceTopicMapping, err error) {
	buf := make([]*model.DeviceTopicMapping, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deviceTopicMappingDo) FindInBatches(result *[]*model.DeviceTopicMapping, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deviceTopicMappingDo) Attrs(attrs ...field.AssignExpr) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deviceTopicMappingDo) Assign(attrs ...field.AssignExpr) IDeviceTopicMappingDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deviceTopicMappingDo) Joins(fields ...field.RelationField) IDeviceTopicMappingDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deviceTopicMappingDo) Preload(fields ...field.RelationField) IDeviceTopicMappingDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deviceTopicMappingDo) FirstOrInit() (*model.DeviceTopicMapping, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceTopicMapping), nil
	}
}

func (d deviceTopicMappingDo) FirstOrCreate() (*model.DeviceTopicMapping, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceTopicMapping), nil
	}
}

func (d deviceTopicMappingDo) FindByPage(offset int, limit int) (result []*model.DeviceTopicMapping, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deviceTopicMappingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deviceTopicMappingDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deviceTopicMappingDo) Delete(models ...*model.DeviceTopicMapping) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deviceTopicMappingDo) withDO(do gen.Dao) *deviceTopicMappingDo {
	d.DO = *do.(*gen.DO)
	return d
}
