// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"project/internal/model"
)

func newDeviceStatusHistory(db *gorm.DB, opts ...gen.DOOption) deviceStatusHistory {
	_deviceStatusHistory := deviceStatusHistory{}

	_deviceStatusHistory.deviceStatusHistoryDo.UseDB(db, opts...)
	_deviceStatusHistory.deviceStatusHistoryDo.UseModel(&model.DeviceStatusHistory{})

	tableName := _deviceStatusHistory.deviceStatusHistoryDo.TableName()
	_deviceStatusHistory.ALL = field.NewAsterisk(tableName)
	_deviceStatusHistory.ID = field.NewInt64(tableName, "id")
	_deviceStatusHistory.TenantID = field.NewString(tableName, "tenant_id")
	_deviceStatusHistory.DeviceID = field.NewString(tableName, "device_id")
	_deviceStatusHistory.Status = field.NewInt16(tableName, "status")
	_deviceStatusHistory.ChangeTime = field.NewTime(tableName, "change_time")

	_deviceStatusHistory.fillFieldMap()

	return _deviceStatusHistory
}

type deviceStatusHistory struct {
	deviceStatusHistoryDo

	ALL        field.Asterisk
	ID         field.Int64
	TenantID   field.String // 租户ID
	DeviceID   field.String // 设备ID
	Status     field.Int16  // 状态: 0-离线 1-在线
	ChangeTime field.Time   // 状态变更时间

	fieldMap map[string]field.Expr
}

func (d deviceStatusHistory) Table(newTableName string) *deviceStatusHistory {
	d.deviceStatusHistoryDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deviceStatusHistory) As(alias string) *deviceStatusHistory {
	d.deviceStatusHistoryDo.DO = *(d.deviceStatusHistoryDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deviceStatusHistory) updateTableName(table string) *deviceStatusHistory {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.TenantID = field.NewString(table, "tenant_id")
	d.DeviceID = field.NewString(table, "device_id")
	d.Status = field.NewInt16(table, "status")
	d.ChangeTime = field.NewTime(table, "change_time")

	d.fillFieldMap()

	return d
}

func (d *deviceStatusHistory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deviceStatusHistory) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 5)
	d.fieldMap["id"] = d.ID
	d.fieldMap["tenant_id"] = d.TenantID
	d.fieldMap["device_id"] = d.DeviceID
	d.fieldMap["status"] = d.Status
	d.fieldMap["change_time"] = d.ChangeTime
}

func (d deviceStatusHistory) clone(db *gorm.DB) deviceStatusHistory {
	d.deviceStatusHistoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deviceStatusHistory) replaceDB(db *gorm.DB) deviceStatusHistory {
	d.deviceStatusHistoryDo.ReplaceDB(db)
	return d
}

type deviceStatusHistoryDo struct{ gen.DO }

type IDeviceStatusHistoryDo interface {
	gen.SubQuery
	Debug() IDeviceStatusHistoryDo
	WithContext(ctx context.Context) IDeviceStatusHistoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDeviceStatusHistoryDo
	WriteDB() IDeviceStatusHistoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDeviceStatusHistoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDeviceStatusHistoryDo
	Not(conds ...gen.Condition) IDeviceStatusHistoryDo
	Or(conds ...gen.Condition) IDeviceStatusHistoryDo
	Select(conds ...field.Expr) IDeviceStatusHistoryDo
	Where(conds ...gen.Condition) IDeviceStatusHistoryDo
	Order(conds ...field.Expr) IDeviceStatusHistoryDo
	Distinct(cols ...field.Expr) IDeviceStatusHistoryDo
	Omit(cols ...field.Expr) IDeviceStatusHistoryDo
	Join(table schema.Tabler, on ...field.Expr) IDeviceStatusHistoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceStatusHistoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDeviceStatusHistoryDo
	Group(cols ...field.Expr) IDeviceStatusHistoryDo
	Having(conds ...gen.Condition) IDeviceStatusHistoryDo
	Limit(limit int) IDeviceStatusHistoryDo
	Offset(offset int) IDeviceStatusHistoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceStatusHistoryDo
	Unscoped() IDeviceStatusHistoryDo
	Create(values ...*model.DeviceStatusHistory) error
	CreateInBatches(values []*model.DeviceStatusHistory, batchSize int) error
	Save(values ...*model.DeviceStatusHistory) error
	First() (*model.DeviceStatusHistory, error)
	Take() (*model.DeviceStatusHistory, error)
	Last() (*model.DeviceStatusHistory, error)
	Find() ([]*model.DeviceStatusHistory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceStatusHistory, err error)
	FindInBatches(result *[]*model.DeviceStatusHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DeviceStatusHistory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDeviceStatusHistoryDo
	Assign(attrs ...field.AssignExpr) IDeviceStatusHistoryDo
	Joins(fields ...field.RelationField) IDeviceStatusHistoryDo
	Preload(fields ...field.RelationField) IDeviceStatusHistoryDo
	FirstOrInit() (*model.DeviceStatusHistory, error)
	FirstOrCreate() (*model.DeviceStatusHistory, error)
	FindByPage(offset int, limit int) (result []*model.DeviceStatusHistory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDeviceStatusHistoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d deviceStatusHistoryDo) Debug() IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Debug())
}

func (d deviceStatusHistoryDo) WithContext(ctx context.Context) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deviceStatusHistoryDo) ReadDB() IDeviceStatusHistoryDo {
	return d.Clauses(dbresolver.Read)
}

func (d deviceStatusHistoryDo) WriteDB() IDeviceStatusHistoryDo {
	return d.Clauses(dbresolver.Write)
}

func (d deviceStatusHistoryDo) Session(config *gorm.Session) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Session(config))
}

func (d deviceStatusHistoryDo) Clauses(conds ...clause.Expression) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deviceStatusHistoryDo) Returning(value interface{}, columns ...string) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deviceStatusHistoryDo) Not(conds ...gen.Condition) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deviceStatusHistoryDo) Or(conds ...gen.Condition) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deviceStatusHistoryDo) Select(conds ...field.Expr) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deviceStatusHistoryDo) Where(conds ...gen.Condition) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deviceStatusHistoryDo) Order(conds ...field.Expr) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deviceStatusHistoryDo) Distinct(cols ...field.Expr) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deviceStatusHistoryDo) Omit(cols ...field.Expr) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deviceStatusHistoryDo) Join(table schema.Tabler, on ...field.Expr) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deviceStatusHistoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deviceStatusHistoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deviceStatusHistoryDo) Group(cols ...field.Expr) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deviceStatusHistoryDo) Having(conds ...gen.Condition) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deviceStatusHistoryDo) Limit(limit int) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deviceStatusHistoryDo) Offset(offset int) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deviceStatusHistoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deviceStatusHistoryDo) Unscoped() IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deviceStatusHistoryDo) Create(values ...*model.DeviceStatusHistory) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deviceStatusHistoryDo) CreateInBatches(values []*model.DeviceStatusHistory, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deviceStatusHistoryDo) Save(values ...*model.DeviceStatusHistory) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deviceStatusHistoryDo) First() (*model.DeviceStatusHistory, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceStatusHistory), nil
	}
}

func (d deviceStatusHistoryDo) Take() (*model.DeviceStatusHistory, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceStatusHistory), nil
	}
}

func (d deviceStatusHistoryDo) Last() (*model.DeviceStatusHistory, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceStatusHistory), nil
	}
}

func (d deviceStatusHistoryDo) Find() ([]*model.DeviceStatusHistory, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeviceStatusHistory), err
}

func (d deviceStatusHistoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeviceStatusHistory, err error) {
	buf := make([]*model.DeviceStatusHistory, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deviceStatusHistoryDo) FindInBatches(result *[]*model.DeviceStatusHistory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deviceStatusHistoryDo) Attrs(attrs ...field.AssignExpr) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deviceStatusHistoryDo) Assign(attrs ...field.AssignExpr) IDeviceStatusHistoryDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deviceStatusHistoryDo) Joins(fields ...field.RelationField) IDeviceStatusHistoryDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deviceStatusHistoryDo) Preload(fields ...field.RelationField) IDeviceStatusHistoryDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deviceStatusHistoryDo) FirstOrInit() (*model.DeviceStatusHistory, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceStatusHistory), nil
	}
}

func (d deviceStatusHistoryDo) FirstOrCreate() (*model.DeviceStatusHistory, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeviceStatusHistory), nil
	}
}

func (d deviceStatusHistoryDo) FindByPage(offset int, limit int) (result []*model.DeviceStatusHistory, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deviceStatusHistoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deviceStatusHistoryDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deviceStatusHistoryDo) Delete(models ...*model.DeviceStatusHistory) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deviceStatusHistoryDo) withDO(do gen.Dao) *deviceStatusHistoryDo {
	d.DO = *do.(*gen.DO)
	return d
}
